### ISSUE TITLE
glob("/media/**/*.jpg") returns directories

### ISSUE THREAD

**Issue by sloganking** [rust-lang/glob#107] opened 2022-01-19 19:43 UTC
The readme states that ``glob("/media/**/*.jpg")`` will return all jpg files in /media/ and all of its sub-directories. However it returns both files and directories who's names end in ``.jpg``.

I have found this workaroud to run after ``glob("/media/**/*.jpg")``, but it seems a little un-ideal.
```rust
let paths: Vec<PathBuf> = paths.into_iter().filter(|e| e.is_file()).collect();
```

**Comment by amtep** [comment] 2022-08-12 16:39
I think this is as intended, since it mimics unix globbing which treats file names and directory names the same.

**Comment by JohnTitor** [comment] 2023-01-11 13:55
Closing in favor of https://github.com/rust-lang/glob/issues/107#issuecomment-1213311308

**Closed by JohnTitor** 2023-01-11 13:55 UTC
